### PR TITLE
Fix syntax failed when plugin not loaded

### PR DESCRIPTION
**Pull request by chemzqm**
FIx syntax vim script failed when sourced without plugin loaded.

### CODE REVIEW

**Comment by jparise** [comment]
@chemzqm could you provide a little more detail about the underlying problem this is meant to address?

**Comment by chemzqm** [comment]
My plugin load only syntax files without plugin files to get the highlights with background neovim, undefined vim variable would cause the highlight fail.

**Comment by jparise** [comment]
@chemzqm Ah, I understand better now. Can you think of a way to avoid duplicating those default values? Also, the unit tests don't appear to pass with this change.

**Comment by jparise** [comment]
Closing this in favor of the autoload approach introduced in #29. I hope it addresses the root problem you encountered, but please open an issue if it doesn't.

**Pull request closed without merging**
