### PR TITLE
Add rescript support

### PR DESCRIPTION
**Pull request by amiralies**

### CODE REVIEW

**Comment by jparise** [comment]
@amiralies Thanks! I'm not familiar with rescript so it will take me a little bit of time to come up to speed on this, but it looks like a simple-enough change.

Could you also update the `README.md` file and documentation (`doc/graphql.txt`) to mention this new language support?

**Comment by amiralies** [comment]
I'll do that, it's basically same as reason though with different start/end tokens

**Review by jparise — APPROVED** [review]

**Comment by jparise** [comment]
I added some minimal documentation in 9a9fe186a73fce636398ee7f851466ef60c9fde5.

**Comment by amiralies** [comment]
Thank you jon!

**Pull request merged**
