### PR TITLE
add support graphql-tools

### PR DESCRIPTION
**Pull request by s97712**
support graphql-tools, use comment to identity schema defined
```
const query = `# gql
{
  user(){
  }
}
`
```

### CODE REVIEW

**Comment by jparise** [comment]
Hi @s97712, can you tell me a little more about this syntax? I'm not able to find references to it anywhere, so I think I'm not looking at the right projects.

- Apollo's [graphql-tools](https://github.com/apollographql/graphql-tools) project doesn't define a template tag itself, but it uses ``gql` `` in [its examples](https://github.com/apollographql/graphql-tools/blob/master/designs/graphql-decorator-spec.md).
- Apollo's [graphql-tag](https://github.com/apollographql/graphql-tag) provides the ``gql` `` template tag, which is what we support.

... so before I add support for this alternate syntax, I'd like to better understand how it is defined and where it is used.

**Comment by s97712** [comment]
```
import { makeExecutableSchema } from 'graphql-tools';
const typeDefs = `
type Author {
  id: ID! # the ! means that every author object _must_ have an id
  firstName: String
  lastName: String
  """
  the list of Posts by this author
  """
  posts: [Post]
}
....
`;
const executableSchema = makeExecutableSchema({
  typeDefs,
  resolvers,
});
```
Like above, it don't need use template tag, so we need another way to identify it as gql language

**Comment by jparise** [comment]
Can you tell me where this comment-style syntax is documented?

**Comment by s97712** [comment]
It just a  comment...
[https://facebook.github.io/graphql/June2018/#sec-Comments](https://facebook.github.io/graphql/June2018/#sec-Comments)

**Comment by jparise** [comment]
I understand now. This is just a convention to trick the editor into highlighting the template as GraphQL.

My main reservation to merging this is that it adds another somewhat expensive (region match) regular expression that will be applied to all JavaScript documents. It also further complicates supporting multiple JavaScript plugins (see #20).

**Comment by s97712** [comment]
I don't know much about its efficiency. Maybe it can be optimized?

**Pull request closed without merging**
